nodeLinker: node-modules

packageExtensions:
  bootstrap@*:
    dependencies:
      popper.js: "*"
  styled-components@*:
    dependencies:
      react-is: "*"

yarnPath: .yarn/releases/yarn-2.2.2.cjs
