nodeLinker: node-modules
# Deploy broken
# nodeLinker: pnp
packageExtensions:
  "@ampproject/toolbox-optimizer@*":
    dependencies:
      cross-fetch: "*"
      dom-serializer: "*"
      postcss: "*"
  bootstrap@*:
    dependencies:
      jquery: "*"
      popper.js: "*"
  sass-loader@*:
    dependencies:
      sass: "*"
  styled-components@*:
    dependencies:
      react-is: "*"
yarnPath: .yarn/releases/yarn-2.1.1.cjs
